receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: '0.0.0.0:9464'
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
processors:
  batch:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/tempo, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
